version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}
    command: sleep infinity
    user: node
    environment:
      DB_URL: mysql+pymysql://root:@db/inovaasc?charset=utf8mb4
      CORS_ORIGIN_REGEX: https://.*\.githubpreview\.dev
      CORS_REGEX: \.githubpreview\.dev$
      NODE_ENV: production
    ports:
      - "3000:3000"
      - "4000:4000"
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mariadb:10.11
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: inovaasc
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -h localhost --silent"]
      interval: 3s
      timeout: 2s
      retries: 40
